//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistrationFormEntities : DbContext
    {
        public RegistrationFormEntities()
            : base("name=RegistrationFormEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginTable> LoginTable { get; set; }
        public virtual DbSet<PasswordTable> PasswordTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
