//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int Id { get; set; }
        public Nullable<int> LoginId { get; set; }
        public Nullable<int> PasswordId { get; set; }
        public string PhoneNumber { get; set; }
        public string E_mail { get; set; }
        public string FirstName { get; set; }
    
        public virtual LoginTable LoginTable { get; set; }
        public virtual PasswordTable PasswordTable { get; set; }
    }
}
